vich_uploader:
    db_driver: orm
    mappings:
        property_audio:
                  uri_prefix: /audio/properties
                  upload_destination: '%kernel.project_dir%/public/audio/properties'
                  namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
